### ISSUE TITLE
[enhancement] Create a single unified method for WalkmodFacade

### ISSUE THREAD

**Issue by abelsromero** [rpau/walkmod-cmd#2]
_As a developer/integrator I'd like to be able to launch walkmod chains through a single method, no matter what configuration I am passing or how the chains are defined._

I've seen that right now the facade offers many methods whose only difference is the number of parameters (error handling, vebose, etc.). Also some require to set the configuration as a [file](https://github.com/rpau/walkmod-core/blob/master/src/main/java/org/walkmod/WalkModFacade.java#L104), and some as a [path](https://github.com/rpau/walkmod-core/blob/master/src/main/java/org/walkmod/WalkModFacade.java#L126).

This approach is correct with the current set of settings, but hinders the possibility to pass more features that may appear in the future.
What I am proposing is creating a single method with the following specification:
* A `Map<String, Object>` object: each parameter can be set with a predefined key: "verbose", "offline", etc. This allows to pass even real object, that could be injected in the context. To ease the configuration, some helper class can be created (here is an example [OptionsBuilder](https://github.com/asciidoctor/asciidoctorj/blob/master/asciidoctorj-core/src/main/java/org/asciidoctor/OptionsBuilder.java)). Optionally, an overloaded method with the helper method could be offered. As an example of future option I'd like to be able to set the base directory for the walkers/visitors, so I can have a folder with the walkmod file in a parent project and the apply the changes to child projects without having to copy it to each one.
* `ConfigurationProvider` instance: right now is it possible to use other providers instead of Ivy, however, the Facade does not allow it. Btw, nothing against ivy, but in corporate enviroments (with proxy and shitty network) Ivy's bootstrap can take quite a long time, whereas being able to pass a direct classloader alreay initialize (e.g. by maven or gradle) can remove that time and simplify the integration with other tools.
* `File or String` walkmod file: I preffer a File, but the main point is defining a single point of entry. I don't have a strong opinion on either options as long as one single option is set. Also I'm thinking that the "walkmod file" could be passed with some interface or wrapper. In the future it would be cool to be able to pass a configuration in some other way, like an object created with a DSL. Anyway, that can be done in the future. wdyt? Should walkmod define it or stick with the file/path? imho, It's a shame ConfigurationProvider name is already taken ><

Current methods can be marked as @deprecated. 

Overall, this proposal avoid changes in the integrators interface regarding the evolution of the API, and makes the Facede more firendly not only to Java but to other languages like Groovy.

wdyt?

**Comment by rpau** [comment]
Hi Abel,

In general, I agree with you with the API that you suggest. I think that are good ideas that can make this API easier to use. 

I think that the first suggestion is necessary, because all started from few options and now it becomes more difficult to set every option. I really would like to have an `OptionBuilder`.

Regarding the second and third point, I think that you are designing the already existing class called `org.walkmod.conf.ConfigurationManager.ConfigurationManager` , which allows to pass the walkmod file (which could be another interface, and the list of `ConfigurationProvider`s). In fact, this is the class that the `WalkmodFacace` uses internally. Isn't it?

How do you want to proceed whatever we decide? Create a pull request or do you need that I apply the changes?

**Comment by abelsromero** [comment]
> How do you want to proceed whatever we decide? Create a pull request or do you need that I apply the changes?

If it's OK for you, you can create a development branch and I can send a PR there.

> Regarding the second and third point, I think that you are designing the already existing class called org.walkmod.conf.ConfigurationManager.ConfigurationManager , which allows to pass the walkmod file (which could be another interface, and the list of ConfigurationProviders). In fact, this is the class that the WalkmodFacace uses internally. Isn't it?

You are right. I'll work arround the idea of using ConfigurationManager and see what I can get. Once the PR is sent we can see alternatives and keep the discussion on it.

Btw, I messed the issue opening it in the wrong project. Can you move it? I have used this before it works quite well: https://github-issue-mover.appspot.com/.

**Comment by rpau** [comment]
This issue was moved to rpau/walkmod-core#18
